name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn style
      - run: yarn lint
      - run: yarn build
